Update whitelist
Keeper-Wallet/Keeper-Wallet-Extension pull request #1008
Opened 2023-06-16 15:23 UTC by domnikov-timofei

2023-06-18 07:33 UTC, smelnikov requested changes

2023-06-18 07:33 UTC, smelnikov commented on src/controllers/NftInfoController.ts
> +
Remove comment

2023-06-18 07:33 UTC, smelnikov commented on src/controllers/NftInfoController.ts
> +    });
It looks like you forgot to remove the debugging code.

2023-06-18 07:33 UTC, smelnikov commented on src/popup.tsx
> +
Remove comment

2023-06-21 13:17 UTC, smelnikov approved these changes

2023-06-21 14:38 UTC, faergeek approved these changes

2023-07-02 05:17 UTC, merged