KEEP-1717.glossary
Keeper-Wallet/Keeper-Wallet-Extension pull request #1064
Opened 2023-07-11 06:13 UTC by elenaili

2023-07-17 07:37 UTC, msmolyakov requested changes

2023-07-17 07:37 UTC, msmolyakov commented on src/ui/components/pages/Info.tsx
> +                href="https://t.me/KeeperWallet"
Let's also add the chat: https://t.me/KeeperCommunity
Probably this should have different logo.

2023-07-18 07:38 UTC, msmolyakov approved these changes

2023-07-19 07:20 UTC, faergeek commented
Moved https://github.com/Keeper-Wallet/Keeper-Wallet-Extension/pull/1083

2023-07-19 07:20 UTC, closed without merging